# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.13-alpine

# Install build dependencies
RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev python3-dev

# Set working directory
WORKDIR /app

# Copy necessary files
COPY pyproject.toml ./
COPY README.md ./
COPY LICENSE ./
COPY src ./src

# Install the package without running scripts if needed
RUN pip install . --no-cache-dir

# Expose port if needed (MCP uses stdio, but may also expose http, so leave optional)

# Command to start the MCP server
CMD ["ttaat", "serve"]
